// utils/constants.js
export const GECKOTERMINAL_CHAIN_MAPPING = {
  'ethereum': 'eth',
  'arbitrum': 'arbitrum',
  'avalanche_c': 'avalanche',
  'bnb': 'bsc',
  'polygon': 'polygon',
  'optimism': 'optimism',
  'base': 'base',
  'zksync': 'zksync',
  'zora': 'zora',
  'linea': 'linea',
  'mantle': 'mantle',
  'scroll': 'scroll',
  'celo': 'celo',
  'opbnb': 'op_bnb',
  'boba': 'boba',
  'metis': 'metis',
  'blast': 'blast',
  'sei': 'sei',
  'kaia': 'kaia',
  'world': 'worldchain',
  'unichain': 'unichain',
  'sonic': 'sonic',
  'berachain': 'berachain',
  'ink': 'ink',
  'mode': 'mode',
  'soneium': 'soneium',
  'monad_testnet': 'monad',
};

export const SUPPORTED_SVM_CHAINS = ['solana', 'eclipse'];

// utils/constants.js
export const chains = [
  { value: '1', label: 'Ethereum', image: '/icons/ethereum.webp', testnet: false },
  { value: '10', label: 'Optimism', image: '/icons/optimism.webp', testnet: false },
  { value: '56', label: 'BNB Chain', image: '/icons/bsc.webp', testnet: false },
  { value: '100', label: 'Gnosis', image: '/icons/gnosis.webp', testnet: false },
  { value: '130', label: 'Unichain', image: '/icons/unichain.webp', testnet: false },
  { value: '137', label: 'Polygon', image: '/icons/polygon.webp', testnet: false },
  { value: '146', label: 'Sonic', image: '/icons/sonic.webp', testnet: false },
  { value: '166', label: 'Omni', image: '/icons/omni.webp', testnet: false },
  { value: '185', label: 'Mint', image: '/icons/mint.webp', testnet: false },
  { value: '204', label: 'opBNB', image: '/icons/opbnb.webp', testnet: false },
  { value: '250', label: 'Fantom', image: '/icons/fantom.webp', testnet: false },
  { value: '324', label: 'zkSync', image: '/icons/zksync.webp', testnet: false },
  { value: '480', label: 'World', image: '/icons/world.webp', testnet: false },
  { value: '1088', label: 'Metis', image: '/icons/metis.webp', testnet: false },
  { value: '1135', label: 'Lisk', image: '/icons/lisk.webp', testnet: false },
  { value: '1329', label: 'Sei', image: '/icons/sei.webp', testnet: false },
  { value: '1868', label: 'Soneium', image: '/icons/soneium.webp', testnet: false },
  { value: '2741', label: 'Abstract', image: '/icons/abstract.webp', testnet: false },
  { value: '5000', label: 'Mantle', image: '/icons/mantle.webp', testnet: false },
  { value: '7560', label: 'Cyber', image: '/icons/cyber.webp', testnet: false },
  { value: '8453', label: 'Base', image: '/icons/base.webp', testnet: false },
  { value: '10143', label: 'Monad', image: '/icons/monad.webp', testnet: true },
  { value: '33139', label: 'Ape Chain', image: '/icons/ape_chain.webp', testnet: false },
  { value: '34443', label: 'Mode', image: '/icons/mode.webp', testnet: false },
  { value: '42161', label: 'Arbitrum', image: '/icons/arbitrum.webp', testnet: false },
  { value: '43114', label: 'Avalanche C', image: '/icons/avalanche_c.webp', testnet: false },
  { value: '42220', label: 'Celo', image: '/icons/celo.webp', testnet: false },
  { value: '57073', label: 'Ink', image: '/icons/ink.webp', testnet: false },
  { value: '59144', label: 'Linea', image: '/icons/linea.webp', testnet: false },
  { value: '80094', label: 'Berachain', image: '/icons/berachain.webp', testnet: false },
  { value: '81457', label: 'Blast', image: '/icons/blast.webp', testnet: false },
  { value: '534352', label: 'Scroll', image: '/icons/scroll.webp', testnet: false },
  { value: '7777777', label: 'Zora', image: '/icons/zora.webp', testnet: false },
  { value: '1380012617', label: 'Rari', image: '/icons/rari.webp', testnet: false },
  { value: 'solana', label: 'Solana', image: '/icons/solana.webp', testnet: false },
  { value: 'tron', label: 'TRON', image: '/icons/tron.webp', testnet: false },
  { value: 'eclipse', label: 'Eclipse', image: '/icons/eclipse.webp', testnet: false }
];

export const mapCoinGeckoChains = (coingeckoChains) => {
  const chainMap = {
    'abstract': '2741',
    'ape_chain': '33139',
    'arbitrum-one': '42161',
    'avalanche_c': '43114',
    'base': '8453',
    'berachain': '80094',
    'blast': '81457',
    'binance-smart-chain': '56',
    'celo': '42220',
    'cyber': '7560',
    'eclipse': 'eclipse',
    'ethereum': '1',
    'fantom': '250',
    'gnosis': '100',
    'ink': '57073',
    'linea': '59144',
    'lisk': '1135',
    'mantle': '5000',
    'metis': '1088',
    'mint': '185',
    'mode': '34443',
    'monad_testnet': '10143',
    'omni': '166',
    'opbnb': '204',
    'optimistic-ethereum': '10',
    'polygon-pos': '137',
    'rari': '1380012617',
    'scroll': '534352',
    'sei': '1329',
    'solana': 'solana',
    'soneium': '1868',
    'sonic': '146',
    'tron': 'tron',
    'unichain': '130',
    'world': '480',
    'zksync': '324',
    'zora': '7777777',
    'solana': 'solana',
    'eclipse': 'eclipse',
  };

  return coingeckoChains
    .filter((chain) => chainMap[chain.id])
    .map((chain) => ({
      value: chainMap[chain.id],
      label: chain.name,
      image: chain.image?.thumb || chains.find((c) => c.value === chainMap[chain.id])?.image || '/icons/default.webp',
      testnet: false,
    }));
};

export const getPlatformImage = (chainId, coingeckoChains) => {
  const chain = coingeckoChains.find((c) => {
    const chainMap = {
      '2741': 'abstract',
      '33139': 'ape_chain',
      '42161': 'arbitrum',
      '43114': 'avalanche_c',
      '8453': 'base',
      '80094': 'berachain',
      '81457': 'blast',
      '56': 'bnb',
      '42220': 'celo',
      '7560': 'cyber',
      '1': 'ethereum',
      '250': 'fantom',
      '100': 'gnosis',
      '57073': 'ink',
      '59144': 'linea',
      '1135': 'lisk',
      '5000': 'mantle',
      '1088': 'metis',
      '185': 'mint',
      '34443': 'mode',
      '166': 'omni',
      '204': 'opbnb',
      '10': 'optimism',
      '137': 'polygon',
      '1380012617': 'rari',
      '534352': 'scroll',
      '1329': 'sei',
      '1868': 'soneium',
      '146': 'sonic',
      '130': 'unichain',
      '480': 'world',
      '324': 'zksync',
      '7777777': 'zora',
      '10143': 'monad_testnet',
      'solana': 'solana',
      'eclipse': 'eclipse',

      // '888888888': 'ancient8',
      // '42170': 'arbitrum_nova',
      // '60808': 'bob',
      // '288': 'boba',
      // '21000000': 'corn',
      // '666666666': 'degen',
      // '14': 'flare',
      // '5112': 'ham',
      // '2911': 'hychain',
      // '8217': 'kaia',
      // '70700': 'proof_of_play',
      // '690': 'redstone',
      // '360': 'shape',
      // '5330': 'superseed',
      // '1923': 'swellchain',
      // '1111': 'wemix',
      // '660279': 'xai',
      // '543210': 'zero_network',
      // '1101': 'zkevm',
    };
    return c.id === chainMap[chainId];
  });
  return chain?.image?.thumb || chains.find((c) => c.value === chainId)?.image || '/icons/default.webp';
};

export const getExplorerUrls = (chainId, txHash, address) => {
  const chain = chains.find((c) => c.value === chainId) || { value: '1', label: 'Ethereum' };
  const baseUrls = {
    '1': 'https://etherscan.io',
    '56': 'https://bscscan.com',
    '204': 'https://opbnb.bscscan.com',
    '250': 'https://ftmscan.com',
    '10': 'https://optimistic.etherscan.io',
    '137': 'https://polygonscan.com',
    '42161': 'https://arbiscan.io',
    '100': 'https://gnosisscan.io',
    '8453': 'https://basescan.org',
    '59144': 'https://lineascan.build',
    '534352': 'https://scrollscan.com',
    '81457': 'https://blastscan.io',
    'solana': 'https://solscan.io',
    'tron': 'https://tronscan.org',
  };
  const baseUrl = baseUrls[chainId] || baseUrls['1'];
  return {
    txUrl: `${baseUrl}/tx/${txHash}`,
    addressUrl: `${baseUrl}/address/${address}`,
  };
};

export const SUPPORTED_CHAINS = [
  { value: 'abstract', chainId: '2741', label: 'Abstract' },
  { value: 'ape_chain', chainId: '33139', label: 'Ape Chain' },
  { value: 'arbitrum', chainId: '42161', label: 'Arbitrum' },
  { value: 'avalanche_c', chainId: '43114', label: 'Avax-C' },
  { value: 'base', chainId: '8453', label: 'Base' },
  { value: 'berachain', chainId: '80094', label: 'Berachain' },
  { value: 'blast', chainId: '81457', label: 'Blast' },
  { value: 'bnb', chainId: '56', label: 'BNB' },
  { value: 'celo', chainId: '42220', label: 'Celo' },
  { value: 'cyber', chainId: '7560', label: 'Cyber' },
  { value: 'ethereum', chainId: '1', label: 'ETH' },
  { value: 'fantom', chainId: '250', label: 'Fantom' },
  { value: 'gnosis', chainId: '100', label: 'Gnosis Chain' },
  { value: 'ink', chainId: '57073', label: 'Ink' },
  { value: 'linea', chainId: '59144', label: 'Linea' },
  { value: 'lisk', chainId: '1135', label: 'Lisk' },
  { value: 'mantle', chainId: '5000', label: 'Mantle' },
  { value: 'metis', chainId: '1088', label: 'Metis' },
  { value: 'mint', chainId: '185', label: 'Mint' },
  { value: 'mode', chainId: '34443', label: 'Mode' },
  { value: 'omni', chainId: '166', label: 'Omni' },
  { value: 'opbnb', chainId: '204', label: 'opBNB' },
  { value: 'optimism', chainId: '10', label: 'Optimism' },
  { value: 'polygon', chainId: '137', label: 'Polygon' },
  { value: 'rari', chainId: '1380012617', label: 'Rari' },
  { value: 'scroll', chainId: '534352', label: 'Scroll' },
  { value: 'sei', chainId: '1329', label: 'Sei' },
  { value: 'soneium', chainId: '1868', label: 'Soneium' },
  { value: 'sonic', chainId: '146', label: 'Sonic' },
  { value: 'unichain', chainId: '130', label: 'Unichain' },
  { value: 'world', chainId: '480', label: 'World' },
  { value: 'zksync', chainId: '324', label: 'zkSync' },
  { value: 'zora', chainId: '7777777', label: 'Zora' },
  { value: 'monad_testnet', chainId: '10143', label: 'Monad Testnet', testnet: true },
  { value: 'solana', chainId: null, label: 'Solana' }, // Added Solana
  { value: 'eclipse', chainId: null, label: 'Eclipse' },

  // { value: 'ancient8', chainId: '888888888', label: 'Ancient8' },
  // { value: 'arbitrum_nova', chainId: '42170', label: 'Arbitrum Nova' },
  // { value: 'bob', chainId: '60808', label: 'BOB' },
  // { value: 'boba', chainId: '288', label: 'Boba' },
  // { value: 'corn', chainId: '21000000', label: 'Corn' },
  // { value: 'degen', chainId: '666666666', label: 'Degen' },
  // { value: 'flare', chainId: '14', label: 'Flare' },
  // { value: 'ham', chainId: '5112', label: 'Ham' },
  // { value: 'hychain', chainId: '2911', label: 'Hychain' },
  // { value: 'kaia', chainId: '8217', label: 'Kaia' },
  // { value: 'proof_of_play', chainId: '70700', label: 'Proof of Play' },
  // { value: 'redstone', chainId: '690', label: 'Redstone' },
  // { value: 'shape', chainId: '360', label: 'Shape' },
  // { value: 'superseed', chainId: '5330', label: 'Superseed' },
  // { value: 'swellchainhome', chainId: '1923', label: 'Swell Chain' },
  // { value: 'wemix', chainId: '1111', label: 'Wemix' },
  // { value: 'zero_network', chainId: '543210', label: 'Zero Network' },
  // { value: 'zkevm', chainId: '1101', label: 'Polygon zkEVM' },
  // { value: 'xai', chainId: '660279', label: 'Xai' },
];

export const CHAIN_MAPPING = {
  'ethereum': { simChain: 'ethereum', chainId: '1' },
  'arbitrum-one': { simChain: 'arbitrum', chainId: '42161' },
  'avalanche': { simChain: 'avalanche_c', chainId: '43114' },
  'binance-smart-chain': { simChain: 'bnb', chainId: '56' },
  'polygon-pos': { simChain: 'polygon', chainId: '137' },
  'optimistic-ethereum': { simChain: 'optimism', chainId: '10' },
  'gnosis': { simChain: 'gnosis', chainId: '100' },
  'base': { simChain: 'base', chainId: '8453' },
  'fantom': { simChain: 'fantom', chainId: '250' },
  'zksync': { simChain: 'zksync', chainId: '324' },
  'zora': { simChain: 'zora', chainId: '7777777' },
  'linea': { simChain: 'linea', chainId: '59144' },
  'mantle': { simChain: 'mantle', chainId: '5000' },
  'scroll': { simChain: 'scroll', chainId: '534352' },
  'celo': { simChain: 'celo', chainId: '42220' },
  'opbnb': { simChain: 'opbnb', chainId: '204' },
  'boba': { simChain: 'boba', chainId: '288' },
  'metis-andromeda': { simChain: 'metis', chainId: '1088' },
  'blast': { simChain: 'blast', chainId: '81457' },
  'sei-network': { simChain: 'sei', chainId: '1329' },
  'kaia': { simChain: 'kaia', chainId: '8217' },
  'world-chain': { simChain: 'world', chainId: '480' },
  'unichain': { simChain: 'unichain', chainId: '130' },
  'sonic': { simChain: 'sonic', chainId: '146' },
  'berachain': { simChain: 'berachain', chainId: '80094' },
  'ink': { simChain: 'ink', chainId: '57073' },
  'mode': { simChain: 'mode', chainId: '34443' },
  'soneium': { simChain: 'soneium', chainId: '1868' },
  'monad': { simChain: 'monad_testnet', chainId: '10143' },
  'abstract': { simChain: 'abstract', chainId: 2741 },
  'rari': { simChain: 'rari', chainId: 1380012617 },
  'lisk': { simChain: 'lisk', chainId: 1135 },
  'cyber': { simChain: 'cyber', chainId: 7560 },
  'xdai': { simChain: 'gnosis', chainId: 100 },
  'solana': { simChain: 'solana', chainId: null },
  'eclipse': { simChain: 'eclipse', chainId: null },
};

// Optional: Include NON_EVM_CHAINS if needed
export const NON_EVM_CHAINS = ['bitcoin', 'ethereum', 'dogecoin', 'solana', 'eclipse'];

export const CHAIN_ID_MAP = {
  abstract: '2741',
  ancient8: '888888888',
  ape_chain: '33139',
  arbitrum: '42161',
  arbitrum_nova: '42170',
  avalanche_c: '43114',
  base: '8453',
  berachain: '80094',
  blast: '81457',
  bnb: '56',
  bob: '60808',
  boba: '288',
  celo: '42220',
  corn: '21000000',
  cyber: '7560',
  degen: '666666666',
  ethereum: '1',
  fantom: '250',
  flare: '14',
  gnosis: '100',
  ham: '5112',
  hychain: '2911',
  ink: '57073',
  kaia: '8217',
  linea: '59144',
  lisk: '1135',
  mantle: '5000',
  metis: '1088',
  mint: '185',
  mode: '34443',
  omni: '166',
  opbnb: '204',
  optimism: '10',
  polygon: '137',
  proof_of_play: '70700',
  rari: '1380012617',
  redstone: '690',
  scroll: '534352',
  sei: '1329',
  shape: '360',
  soneium: '1868',
  sonic: '146',
  superseed: '5330',
  swellchain: '1923',
  unichain: '130',
  wemix: '1111',
  world: '480',
  xai: '660279',
  zero_network: '543210',
  zkevm: '1101',
  zksync: '324',
  zora: '7777777',
  monad_testnet: '10143',
  solana: 'solana',
  eclipse: 'eclipse',
};

export const CHAIN_EXPLORER_MAP = {
  abstract: { baseUrl: 'https://explorer.abstractscan.io', supportsTx: true, supportsAddress: true },
  ancient8: { baseUrl: 'https://scan.ancient8.gg', supportsTx: true, supportsAddress: true },
  ape_chain: { baseUrl: 'https://explorer.apescan.io', supportsTx: true, supportsAddress: true },
  arbitrum: { baseUrl: 'https://arbiscan.io', supportsTx: true, supportsAddress: true },
  arbitrum_nova: { baseUrl: 'https://nova.arbiscan.io', supportsTx: true, supportsAddress: true },
  avalanche_c: { baseUrl: 'https://snowtrace.io', supportsTx: true, supportsAddress: true },
  base: { baseUrl: 'https://basescan.org', supportsTx: true, supportsAddress: true },
  berachain: { baseUrl: 'https://berascan.io', supportsTx: true, supportsAddress: true },
  blast: { baseUrl: 'https://blastscan.io', supportsTx: true, supportsAddress: true },
  bnb: { baseUrl: 'https://bscscan.com', supportsTx: true, supportsAddress: true },
  bob: { baseUrl: 'https://explorer.gobob.xyz', supportsTx: true, supportsAddress: true },
  boba: { baseUrl: 'https://bobascan.com', supportsTx: true, supportsAddress: true },
  celo: { baseUrl: 'https://celoscan.io', supportsTx: true, supportsAddress: true },
  corn: { baseUrl: 'https://explorer.cornscan.io', supportsTx: true, supportsAddress: true },
  cyber: { baseUrl: 'https://cyberscan.co', supportsTx: true, supportsAddress: true },
  degen: { baseUrl: 'https://explorer.degen.tips', supportsTx: true, supportsAddress: true },
  ethereum: { baseUrl: 'https://etherscan.io', supportsTx: true, supportsAddress: true },
  fantom: { baseUrl: 'https://ftmscan.com', supportsTx: true, supportsAddress: true },
  flare: { baseUrl: 'https://flarescan.com', supportsTx: true, supportsAddress: true },
  gnosis: { baseUrl: 'https://gnosisscan.io', supportsTx: true, supportsAddress: true },
  ham: { baseUrl: 'https://explorer.hamchain.io', supportsTx: true, supportsAddress: true },
  hychain: { baseUrl: 'https://explorer.hychain.com', supportsTx: true, supportsAddress: true },
  ink: { baseUrl: 'https://explorer.inkchain.io', supportsTx: true, supportsAddress: true },
  kaia: { baseUrl: 'https://kaiascan.io', supportsTx: true, supportsAddress: true },
  linea: { baseUrl: 'https://lineascan.build', supportsTx: true, supportsAddress: true },
  lisk: { baseUrl: 'https://liskscan.com', supportsTx: true, supportsAddress: true },
  mantle: { baseUrl: 'https://mantlescan.xyz', supportsTx: true, supportsAddress: true },
  metis: { baseUrl: 'https://andromeda-explorer.metis.io', supportsTx: true, supportsAddress: true },
  mint: { baseUrl: 'https://explorer.mintchain.io', supportsTx: true, supportsAddress: true },
  mode: { baseUrl: 'https://modescan.io', supportsTx: true, supportsAddress: true },
  monad_testnet: { baseUrl: 'https://explorer.monad.xyz', supportsTx: true, supportsAddress: true },
  omni: { baseUrl: 'https://explorer.omni.network', supportsTx: true, supportsAddress: true },
  opbnb: { baseUrl: 'https://opbnbscan.com', supportsTx: true, supportsAddress: true },
  optimism: { baseUrl: 'https://optimistic.etherscan.io', supportsTx: true, supportsAddress: true },
  polygon: { baseUrl: 'https://polygonscan.com', supportsTx: true, supportsAddress: true },
  proof_of_play: { baseUrl: 'https://explorer.proofofplay.io', supportsTx: true, supportsAddress: true },
  rari: { baseUrl: 'https://rarichain.org', supportsTx: true, supportsAddress: true },
  redstone: { baseUrl: 'https://redstonescan.com', supportsTx: true, supportsAddress: true },
  scroll: { baseUrl: 'https://scrollscan.com', supportsTx: true, supportsAddress: true },
  sei: { baseUrl: 'https://seiscan.app', supportsTx: true, supportsAddress: true },
  shape: { baseUrl: 'https://shapescan.xyz', supportsTx: true, supportsAddress: true },
  soneium: { baseUrl: 'https://explorer.soneium.org', supportsTx: true, supportsAddress: true },
  sonic: { baseUrl: 'https://sonicscan.io', supportsTx: true, supportsAddress: true },
  superseed: { baseUrl: 'https://superseedscan.io', supportsTx: true, supportsAddress: true },
  swellchain: { baseUrl: 'https://swellscan.io', supportsTx: true, supportsAddress: true },
  unichain: { baseUrl: 'https://unichain-sepolia.explorer.caldera.xyz', supportsTx: true, supportsAddress: true },
  wemix: { baseUrl: 'https://wemixscan.com', supportsTx: true, supportsAddress: true },
  world: { baseUrl: 'https://worldscan.io', supportsTx: true, supportsAddress: true },
  xai: { baseUrl: 'https://xaiscan.io', supportsTx: true, supportsAddress: true },
  zero_network: { baseUrl: 'https://zeroscan.io', supportsTx: true, supportsAddress: true },
  zkevm: { baseUrl: 'https://zkevm.polygonscan.com', supportsTx: true, supportsAddress: true },
  zksync: { baseUrl: 'https://explorer.zksync.io', supportsTx: true, supportsAddress: true },
  zora: { baseUrl: 'https://zora.superscan.network', supportsTx: true, supportsAddress: true },
};

export const CHAIN_ID_TO_NAME = {
  '2741': 'abstract',
  '888888888': 'ancient8',
  '33139': 'ape_chain',
  '42161': 'arbitrum',
  '42170': 'arbitrum_nova',
  '43114': 'avalanche_c',
  '8453': 'base',
  '80094': 'berachain',
  '81457': 'blast',
  '56': 'bnb',
  '60808': 'bob',
  '288': 'boba',
  '42220': 'celo',
  '21000000': 'corn',
  '7560': 'cyber',
  '666666666': 'degen',
  '1': 'ethereum',
  '250': 'fantom',
  '14': 'flare',
  '100': 'gnosis',
  '5112': 'ham',
  '2911': 'hychain',
  '57073': 'ink',
  '8217': 'kaia',
  '59144': 'linea',
  '1135': 'lisk',
  '5000': 'mantle',
  '1088': 'metis',
  '185': 'mint',
  '34443': 'mode',
  '166': 'omni',
  '204': 'opbnb',
  '10': 'optimism',
  '137': 'polygon',
  '70700': 'proof_of_play',
  '1380012617': 'rari',
  '690': 'redstone',
  '534352': 'scroll',
  '1329': 'sei',
  '360': 'shape',
  '1868': 'soneium',
  '146': 'sonic',
  '5330': 'superseed',
  '1923': 'swellchain',
  '130': 'unichain',
  '1111': 'wemix',
  '480': 'world',
  '660279': 'xai',
  '543210': 'zero_network',
  '1101': 'zkevm',
  '324': 'zksync',
  '7777777': 'zora',
  '10143': 'monad_testnet',
  'solana': 'solana',
  'eclipse': 'eclipse',
};